apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web
  namespace: demo
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: /data/www
  persistentVolumeReclaimPolicy: Retain
---
ipiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-web
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: web-nodejs
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: $DOCKER_IMAGE_NAME
        name: nodejs-app
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: web-data
          mountPath: /usr/src/app
      volumes:
      - name: web-data
        persistentVolumeClaim:
          claimName: pv-web

---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: demo
spec:
  selector:
    app: web
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 32080
  type: NodePort
