
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web-nodejs
  namespace: kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: $DOCKER_IMAGE_NAME
        name: nodejs-app
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: web-data
          mountPath: /usr/src/app
      volumes:
      - name: web-data
        persistentVolumeClaim:
          claimName: pv-web

---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: kube
spec:
  selector:
    app: web
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
  type: NodePort
